services:

  backend:

    image: 817137372823.dkr.ecr.us-east-1.amazonaws.com/college-event-portal-backend:latest

    environment:
      DB_HOST: college-event-db.c23oo8qukcn2.us-east-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: userdata
      DB_NAME: college_event_db

    networks:
      - college-network


  frontend:

    image: 817137372823.dkr.ecr.us-east-1.amazonaws.com/college-event-portal-frontend:latest

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - college-network


networks:

  college-network:
